### ISSUE TITLE
docker-compose run --rm django python manage.py createsuperuser

### ISSUE THREAD

**Issue by rallep71** [2stacks/freeradius-django#11]
docker-compose run --rm django python manage.py createsuperuser
Starting freeradius-django_postgres_1 ... done
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...

**Comment by 2stacks** [comment]
What's the output of `docker-compose ps -a` and `docker-compose logs postgres`?

**Comment by rallep71** [comment]
docker-compose ps

freeradius-django_django_1       /entrypoint /start               Up           0.0.0.0:8000->8000/tcp                      
freeradius-django_freeradius_1   /docker-entrypoint.sh /sta ...   Up           0.0.0.0:1812->1812/udp,                     
                                                                               0.0.0.0:1813->1813/udp                      
freeradius-django_postgres_1     docker-entrypoint.sh postg ...   Restarting

and

docker-compose logs postgres

r root
postgres_1    | 2019-12-28 07:10:05.544 UTC [1] LOG:  database system is shut down
postgres_1    | 
postgres_1    | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1    | 
postgres_1    | 2019-12-28 07:10:58.752 UTC [1] FATAL:  private key file "/server.key" must be owned by the database user or root
postgres_1    | 2019-12-28 07:10:58.753 UTC [1] LOG:  database system is shut down

**Comment by 2stacks** [comment]
That issue is covered in the README.  You need to change the permissions on the postgresql 'server.key'
 https://github.com/2stacks/freeradius-django/blob/master/docs/README.md#generate-new-certs

**Comment by rallep71** [comment]
Ok, issue solved,

next problem. 

 freeradius-django_postgres_1

postgres_1    | 2019-12-29 09:05:00.651 UTC [761] FATAL:  database "radius" does not exist
postgres_1    | 2019-12-29 09:05:01.838 UTC [762] FATAL:  database "radius" does not exist
postgres_1    | 2019-12-29 09:05:03.002 UTC [763] FATAL:  database "radius" does not exist
postgres_1    | 2019-12-29 09:05:04.168 UTC [764] FATAL:  database "radius" does not exist
postgres_1    | 2019-12-29 09:05:05.340 UTC [765] FATAL:  database "radius" does not exist

PostgreSQL Database directory appears to contain a database; Skipping initialization




2019-12-29 09:56:02.137 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432


2019-12-29 09:56:02.137 UTC [1] LOG:  listening on IPv6 address "::", port 5432


2019-12-29 09:56:02.149 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"


2019-12-29 09:56:02.194 UTC [20] LOG:  database system was shut down at 2019-12-29 09:55:59 UTC


2019-12-29 09:56:02.201 UTC [1] LOG:  database system is ready to accept connections


2019-12-29 09:56:03.107 UTC [27] FATAL:  database "radius" does not exist


2019-12-29 09:56:04.310 UTC [28] FATAL:  database "radius" does not exist


2019-12-29 09:56:05.550 UTC [29] FATAL:  database "radius" does not exist


2019-12-29 09:56:06.747 UTC [30] FATAL:  database "radius" does not exist


is it possible there's something wrong here already?

https://github.com/2stacks/freeradius-django/tree/master/compose/postgres/init


my version
#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

CREATE DATABASE radius;
CREATE USER debug WITH PASSWORD 'debug';
GRANT ALL PRIVILEGES ON DATABASE "radius" to debug;
EOSQL

version on github
https://github.com/2stacks/freeradius-django/tree/master/compose/postgres/init

iv not testet.

**Comment by 2stacks** [comment]
Since the key wasn't readable the first time you brought up the stack the database didn't build correctly.  You'll need to start over by running;

`docker-compose down -v` to remove the existing database volume

and then bring up the stack again with 

`docker-compose up -d`

**Comment by rallep71** [comment]
ok, thanks for your help, here is the next problem

freeradius-django_django_1

django.db.utils.OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Address not available
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?

and
freeradius-django_postgres_1

PostgreSQL init process complete; ready for start up.
2019-12-29 16:08:35.084 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-12-29 16:08:35.084 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2019-12-29 16:08:35.100 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2019-12-29 16:08:35.130 UTC [44] LOG:  database system was shut down at 2019-12-29 16:08:34 UTC
2019-12-29 16:08:35.149 UTC [1] LOG:  database system is ready to accept connections

**Comment by 2stacks** [comment]
What's the output of `docker-compose ps -a`?  Did you edit the DB settings per docs?  What's the contents of this file?

./django-freeradius/tests/local_settings.py

**Comment by rallep71** [comment]
freeradius-django_django_1       /entrypoint /start               Exit 1                                        
freeradius-django_freeradius_1   /docker-entrypoint.sh /sta ...   Up       0.0.0.0:1812->1812/udp,              
                                                                           0.0.0.0:1813->1813/udp               
freeradius-django_postgres_1     docker-entrypoint.sh postg ...   Up       127.0.0.1:5432->5432/tcp 

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'radius',
        'USER': 'debug',
        'PASSWORD': 'debug',
        'HOST': 'localhost',
        'PORT': '5432',
        'OPTIONS': {'sslmode': 'require'},
    },
}

ALLOWED_HOSTS = ['*']

**Comment by 2stacks** [comment]
What's the full output of 

`docker-compose ps -a`
`docker-compose logs django`

**Comment by rallep71** [comment]
docker-compose logs django
Attaching to freeradius-django_django_1
django_1      | Waiting for PostgreSQL to become available...
django_1      | PostgreSQL is available
django_1      | /usr/local/lib/python3.8/site-packages/environ/environ.py:628: UserWarning: /app/.env doesn't exist - if you're not configuring your environment separately, create one.
django_1      |   warnings.warn(
django_1      | /usr/local/lib/python3.8/site-packages/weasyprint/fonts.py:229: UserWarning: FontConfig: No fonts configured. Expect ugly output.
django_1      |   warnings.warn(
django_1      | Traceback (most recent call last):
django_1      |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
django_1      |     self.connect()
django_1      |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 195, in connect
django_1      |     self.connection = self.get_new_connection(conn_params)
django_1      |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
django_1      |     connection = Database.connect(**conn_params)
django_1      |   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
django_1      |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django_1      | psycopg2.OperationalError: could not connect to server: Connection refused
django_1      | 	Is the server running on host "localhost" (127.0.0.1) and accepting
django_1      | 	TCP/IP connections on port 5432?
django_1      | could not connect to server: Address not available
django_1      | 	Is the server running on host "localhost" (::1) and accepting
django_1      | 	TCP/IP connections on port 5432?
django_1      | 
django_1      | 
django_1      | The above exception was the direct cause of the following exception:
django_1      | 
django_1      | Traceback (most recent call last):
django_1      |   File "manage.py", line 10, in <module>
django_1      |     execute_from_command_line(sys.argv)
django_1      |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
django_1      |     utility.execute()
django_1      |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
django_1      |     self.fetch_command(subcommand).run_from_argv(self.argv)
django_1      |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
django_1      |     self.execute(*args, **cmd_options)
django_1      |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
django_1      |     output = self.handle(*args, **options)
django_1      |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
django_1      |     res = handle_func(*args, **kwargs)
django_1      |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 87, in handle
django_1      |     executor = MigrationExecutor(connection, self.migration_progress_callback)
django_1      |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
django_1      |     self.loader = MigrationLoader(self.connection)
django_1      |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 49, in __init__
django_1      |     self.build_graph()
django_1      |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 212, in build_graph
django_1      |     self.applied_migrations = recorder.applied_migrations()
django_1      |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
django_1      |     if self.has_table():
django_1      |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 56, in has_table
django_1      |     return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
django_1      |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 256, in cursor
django_1      |     return self._cursor()
django_1      |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 233, in _cursor
django_1      |     self.ensure_connection()
django_1      |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
django_1      |     self.connect()
django_1      |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
django_1      |     raise dj_exc_value.with_traceback(traceback) from exc_value
django_1      |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
django_1      |     self.connect()
django_1      |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 195, in connect
django_1      |     self.connection = self.get_new_connection(conn_params)
django_1      |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
django_1      |     connection = Database.connect(**conn_params)
django_1      |   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
django_1      |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django_1      | django.db.utils.OperationalError: could not connect to server: Connection refused
django_1      | 	Is the server running on host "localhost" (127.0.0.1) and accepting
django_1      | 	TCP/IP connections on port 5432?
django_1      | could not connect to server: Address not available
django_1      | 	Is the server running on host "localhost" (::1) and accepting
django_1      | 	TCP/IP connections on port 5432?

with docker-compose ps -a iv a problem

linux@linuxasus:/media/Data/DjangoRadius/freeradius-django$ docker-compose ps -a
List containers.

Usage: ps [options] [SERVICE...]

Options:
    -q, --quiet          Only display IDs
    --services           Display services
    --filter KEY=VAL     Filter services by a property

**Comment by rallep71** [comment]
linux@linuxasus:/media/Data/DjangoRadius/freeradius-django$ docker-compose ps --services
postgres
django
freeradius

**Comment by rallep71** [comment]
ok, iv edit
local settings

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'radius',
        'USER': 'debug',
        'PASSWORD': 'debug',
        'HOST': 'postgres',
        'PORT': '5432',
        'OPTIONS': {'sslmode': 'require'},
    },
}

ALLOWED_HOSTS = ['*']

now it work, 

http://0.0.0.0:8000/admin/

**Comment by rallep71** [comment]
one more question, how can I create a login to administer it?

with this?


docker-compose run --rm django python manage.py createsuperuser

**Comment by rallep71** [comment]
Great Work, TXH for Your Help!!!!

I will Testet it with my mikrotik router, wlan with eab, i hope it will work ;)

Thx a lot

**Comment by 2stacks** [comment]
No problem and thank you.  I hand't realized until now that the Docs had the wrong hostname for the DB (localhost vs postgres).  I'll update them ASAP. You can let me know how your testing goes via e-mail.

**Comment by rallep71** [comment]
ok, i will do that ;) next problem iv found :)
